import Control.Exception
import System.IO.Unsafe

main :: IO ()
main = print $ unexceptional $ head [1 `div` 0]


unexceptional :: a -> Either SomeException a
unexceptional x = unsafePerformIO $ do
    try (x `seq` return x)











































































































